- hosts: allserver
  vars:
    image: charumha/nginx-games
  tasks:
    - name: install inginx
      apt:
       name: "{{ item }}"
       state: present
      loop:
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == "Debian"

    - name: install python-docker centos
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release #baca repo centos, update list repo
        - python3
        - python3-docker #package utk hub ansible ke docker di centos 
      when: ansible_facts['os_family'] == "RedHat"

    - name: pull image
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes

    - name: rub container
      docker_container:
        name: docker-ansible-games #nama container
        image: "{{ image }}"
        state: started
        published_ports:
          - 10000:80
        recreate: yes
